<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TradePet.Application\TradePet.Application.csproj" />
    <ProjectReference Include="..\..\src\TradePet.Infrastructure\TradePet.Infrastructure.csproj" />
  </ItemGroup>
</Project>
